#include "variant.h"

#include <stdint.h>

const PinDescription g_APinDescription[PINS_COUNT] = {
    {GPIOA, DL_GPIO_PIN_11, 11, IOMUX_PINCM22, 0xFF, PWM_TIMER_NONE, 0, 0, DL_GPIO_PIN_11_EDGE_DISABLE, DL_GPIO_PIN_11_EDGE_RISE, DL_GPIO_PIN_11_EDGE_FALL, DL_GPIO_PIN_11_EDGE_RISE_FALL},
    {GPIOA, DL_GPIO_PIN_10, 10, IOMUX_PINCM21, 0xFF, PWM_TIMER_NONE, 0, 0, DL_GPIO_PIN_10_EDGE_DISABLE, DL_GPIO_PIN_10_EDGE_RISE, DL_GPIO_PIN_10_EDGE_FALL, DL_GPIO_PIN_10_EDGE_RISE_FALL},
    {GPIOA, DL_GPIO_PIN_18, 18, IOMUX_PINCM40, 0xFF, PWM_TIMER_NONE, 0, 0, DL_GPIO_PIN_18_EDGE_DISABLE, DL_GPIO_PIN_18_EDGE_RISE, DL_GPIO_PIN_18_EDGE_FALL, DL_GPIO_PIN_18_EDGE_RISE_FALL},
    {GPIOA, DL_GPIO_PIN_0, 0, IOMUX_PINCM1, 0xFF, PWM_TIMER_TIMA0, 0, IOMUX_PINCM1_PF_TIMA0_CCP0, DL_GPIO_PIN_0_EDGE_DISABLE, DL_GPIO_PIN_0_EDGE_RISE, DL_GPIO_PIN_0_EDGE_FALL, DL_GPIO_PIN_0_EDGE_RISE_FALL},
    {GPIOA, DL_GPIO_PIN_1, 1, IOMUX_PINCM2, 0xFF, PWM_TIMER_TIMA0, 1, IOMUX_PINCM2_PF_TIMA0_CCP1, DL_GPIO_PIN_1_EDGE_DISABLE, DL_GPIO_PIN_1_EDGE_RISE, DL_GPIO_PIN_1_EDGE_FALL, DL_GPIO_PIN_1_EDGE_RISE_FALL},
    {GPIOB, DL_GPIO_PIN_21, 21, IOMUX_PINCM49, 0xFF, PWM_TIMER_NONE, 0, 0, DL_GPIO_PIN_21_EDGE_DISABLE, DL_GPIO_PIN_21_EDGE_RISE, DL_GPIO_PIN_21_EDGE_FALL, DL_GPIO_PIN_21_EDGE_RISE_FALL},
    {GPIOB, DL_GPIO_PIN_22, 22, IOMUX_PINCM50, 0xFF, PWM_TIMER_TIMG8, 1, IOMUX_PINCM50_PF_TIMG8_CCP1, DL_GPIO_PIN_22_EDGE_DISABLE, DL_GPIO_PIN_22_EDGE_RISE, DL_GPIO_PIN_22_EDGE_FALL, DL_GPIO_PIN_22_EDGE_RISE_FALL},
    {GPIOB, DL_GPIO_PIN_26, 26, IOMUX_PINCM57, 0xFF, PWM_TIMER_TIMA0, 3, IOMUX_PINCM57_PF_TIMA0_CCP3, DL_GPIO_PIN_26_EDGE_DISABLE, DL_GPIO_PIN_26_EDGE_RISE, DL_GPIO_PIN_26_EDGE_FALL, DL_GPIO_PIN_26_EDGE_RISE_FALL},
    {GPIOB, DL_GPIO_PIN_27, 27, IOMUX_PINCM58, 0xFF, PWM_TIMER_NONE, 0, 0, DL_GPIO_PIN_27_EDGE_DISABLE, DL_GPIO_PIN_27_EDGE_RISE, DL_GPIO_PIN_27_EDGE_FALL, DL_GPIO_PIN_27_EDGE_RISE_FALL},
    {GPIOB, DL_GPIO_PIN_2, 2, IOMUX_PINCM15, 0xFF, PWM_TIMER_NONE, 0, 0, DL_GPIO_PIN_2_EDGE_DISABLE, DL_GPIO_PIN_2_EDGE_RISE, DL_GPIO_PIN_2_EDGE_FALL, DL_GPIO_PIN_2_EDGE_RISE_FALL},
    {GPIOB, DL_GPIO_PIN_3, 3, IOMUX_PINCM16, 0xFF, PWM_TIMER_NONE, 0, 0, DL_GPIO_PIN_3_EDGE_DISABLE, DL_GPIO_PIN_3_EDGE_RISE, DL_GPIO_PIN_3_EDGE_FALL, DL_GPIO_PIN_3_EDGE_RISE_FALL},
    {GPIOB, DL_GPIO_PIN_6, 6, IOMUX_PINCM23, 0xFF, PWM_TIMER_TIMG8, 0, IOMUX_PINCM23_PF_TIMG8_CCP0, DL_GPIO_PIN_6_EDGE_DISABLE, DL_GPIO_PIN_6_EDGE_RISE, DL_GPIO_PIN_6_EDGE_FALL, DL_GPIO_PIN_6_EDGE_RISE_FALL},
    {GPIOB, DL_GPIO_PIN_7, 7, IOMUX_PINCM24, 0xFF, PWM_TIMER_TIMG8, 1, IOMUX_PINCM24_PF_TIMG8_CCP1, DL_GPIO_PIN_7_EDGE_DISABLE, DL_GPIO_PIN_7_EDGE_RISE, DL_GPIO_PIN_7_EDGE_FALL, DL_GPIO_PIN_7_EDGE_RISE_FALL},
    {GPIOB, DL_GPIO_PIN_8, 8, IOMUX_PINCM25, 0xFF, PWM_TIMER_TIMA0, 0, IOMUX_PINCM25_PF_TIMA0_CCP0, DL_GPIO_PIN_8_EDGE_DISABLE, DL_GPIO_PIN_8_EDGE_RISE, DL_GPIO_PIN_8_EDGE_FALL, DL_GPIO_PIN_8_EDGE_RISE_FALL},
    {GPIOB, DL_GPIO_PIN_9, 9, IOMUX_PINCM26, 0xFF, PWM_TIMER_TIMA0, 1, IOMUX_PINCM26_PF_TIMA0_CCP1, DL_GPIO_PIN_9_EDGE_DISABLE, DL_GPIO_PIN_9_EDGE_RISE, DL_GPIO_PIN_9_EDGE_FALL, DL_GPIO_PIN_9_EDGE_RISE_FALL},
    {GPIOA, DL_GPIO_PIN_25, 25, IOMUX_PINCM55, 2, PWM_TIMER_TIMA0, 3, IOMUX_PINCM55_PF_TIMA0_CCP3, DL_GPIO_PIN_25_EDGE_DISABLE, DL_GPIO_PIN_25_EDGE_RISE, DL_GPIO_PIN_25_EDGE_FALL, DL_GPIO_PIN_25_EDGE_RISE_FALL},
    {GPIOB, DL_GPIO_PIN_25, 25, IOMUX_PINCM56, 4, PWM_TIMER_NONE, 0, 0, DL_GPIO_PIN_25_EDGE_DISABLE, DL_GPIO_PIN_25_EDGE_RISE, DL_GPIO_PIN_25_EDGE_FALL, DL_GPIO_PIN_25_EDGE_RISE_FALL},
};

extern "C" void initVariant(void)
{
}
