#include "variant.h"

#include <stdint.h>

const PinDescription g_APinDescription[PINS_COUNT] = {
    {GPIOA, DL_GPIO_PIN_11, 11, IOMUX_PINCM22, 0xFF, PWM_TIMER_NONE, 0, 0, DL_GPIO_PIN_11_EDGE_DISABLE, DL_GPIO_PIN_11_EDGE_RISE, DL_GPIO_PIN_11_EDGE_FALL, DL_GPIO_PIN_11_EDGE_RISE_FALL},
    {GPIOA, DL_GPIO_PIN_10, 10, IOMUX_PINCM21, 0xFF, PWM_TIMER_NONE, 0, 0, DL_GPIO_PIN_10_EDGE_DISABLE, DL_GPIO_PIN_10_EDGE_RISE, DL_GPIO_PIN_10_EDGE_FALL, DL_GPIO_PIN_10_EDGE_RISE_FALL},
    {GPIOA, DL_GPIO_PIN_18, 18, IOMUX_PINCM40, 0xFF, PWM_TIMER_NONE, 0, 0, DL_GPIO_PIN_18_EDGE_DISABLE, DL_GPIO_PIN_18_EDGE_RISE, DL_GPIO_PIN_18_EDGE_FALL, DL_GPIO_PIN_18_EDGE_RISE_FALL},
    {GPIOA, DL_GPIO_PIN_0, 0, IOMUX_PINCM1, 0xFF, PWM_TIMER_TIMA0, 0, IOMUX_PINCM1_PF_TIMA0_CCP0, DL_GPIO_PIN_0_EDGE_DISABLE, DL_GPIO_PIN_0_EDGE_RISE, DL_GPIO_PIN_0_EDGE_FALL, DL_GPIO_PIN_0_EDGE_RISE_FALL},
    {GPIOA, DL_GPIO_PIN_1, 1, IOMUX_PINCM2, 0xFF, PWM_TIMER_TIMA0, 1, IOMUX_PINCM2_PF_TIMA0_CCP1, DL_GPIO_PIN_1_EDGE_DISABLE, DL_GPIO_PIN_1_EDGE_RISE, DL_GPIO_PIN_1_EDGE_FALL, DL_GPIO_PIN_1_EDGE_RISE_FALL},
    {GPIOB, DL_GPIO_PIN_21, 21, IOMUX_PINCM49, 0xFF, PWM_TIMER_NONE, 0, 0, DL_GPIO_PIN_21_EDGE_DISABLE, DL_GPIO_PIN_21_EDGE_RISE, DL_GPIO_PIN_21_EDGE_FALL, DL_GPIO_PIN_21_EDGE_RISE_FALL},
    {GPIOB, DL_GPIO_PIN_22, 22, IOMUX_PINCM50, 0xFF, PWM_TIMER_TIMG8, 1, IOMUX_PINCM50_PF_TIMG8_CCP1, DL_GPIO_PIN_22_EDGE_DISABLE, DL_GPIO_PIN_22_EDGE_RISE, DL_GPIO_PIN_22_EDGE_FALL, DL_GPIO_PIN_22_EDGE_RISE_FALL},
    {GPIOB, DL_GPIO_PIN_26, 26, IOMUX_PINCM57, 0xFF, PWM_TIMER_TIMA0, 3, IOMUX_PINCM57_PF_TIMA0_CCP3, DL_GPIO_PIN_26_EDGE_DISABLE, DL_GPIO_PIN_26_EDGE_RISE, DL_GPIO_PIN_26_EDGE_FALL, DL_GPIO_PIN_26_EDGE_RISE_FALL},
    {GPIOB, DL_GPIO_PIN_27, 27, IOMUX_PINCM58, 0xFF, PWM_TIMER_NONE, 0, 0, DL_GPIO_PIN_27_EDGE_DISABLE, DL_GPIO_PIN_27_EDGE_RISE, DL_GPIO_PIN_27_EDGE_FALL, DL_GPIO_PIN_27_EDGE_RISE_FALL},
    {GPIOB, DL_GPIO_PIN_2, 2, IOMUX_PINCM15, 0xFF, PWM_TIMER_NONE, 0, 0, DL_GPIO_PIN_2_EDGE_DISABLE, DL_GPIO_PIN_2_EDGE_RISE, DL_GPIO_PIN_2_EDGE_FALL, DL_GPIO_PIN_2_EDGE_RISE_FALL},
    {GPIOB, DL_GPIO_PIN_3, 3, IOMUX_PINCM16, 0xFF, PWM_TIMER_NONE, 0, 0, DL_GPIO_PIN_3_EDGE_DISABLE, DL_GPIO_PIN_3_EDGE_RISE, DL_GPIO_PIN_3_EDGE_FALL, DL_GPIO_PIN_3_EDGE_RISE_FALL},
    {GPIOB, DL_GPIO_PIN_6, 6, IOMUX_PINCM23, 0xFF, PWM_TIMER_TIMG8, 0, IOMUX_PINCM23_PF_TIMG8_CCP0, DL_GPIO_PIN_6_EDGE_DISABLE, DL_GPIO_PIN_6_EDGE_RISE, DL_GPIO_PIN_6_EDGE_FALL, DL_GPIO_PIN_6_EDGE_RISE_FALL},
    {GPIOB, DL_GPIO_PIN_7, 7, IOMUX_PINCM24, 0xFF, PWM_TIMER_TIMG8, 1, IOMUX_PINCM24_PF_TIMG8_CCP1, DL_GPIO_PIN_7_EDGE_DISABLE, DL_GPIO_PIN_7_EDGE_RISE, DL_GPIO_PIN_7_EDGE_FALL, DL_GPIO_PIN_7_EDGE_RISE_FALL},
    {GPIOB, DL_GPIO_PIN_8, 8, IOMUX_PINCM25, 0xFF, PWM_TIMER_TIMA0, 0, IOMUX_PINCM25_PF_TIMA0_CCP0, DL_GPIO_PIN_8_EDGE_DISABLE, DL_GPIO_PIN_8_EDGE_RISE, DL_GPIO_PIN_8_EDGE_FALL, DL_GPIO_PIN_8_EDGE_RISE_FALL},
    {GPIOB, DL_GPIO_PIN_9, 9, IOMUX_PINCM26, 0xFF, PWM_TIMER_TIMA0, 1, IOMUX_PINCM26_PF_TIMA0_CCP1, DL_GPIO_PIN_9_EDGE_DISABLE, DL_GPIO_PIN_9_EDGE_RISE, DL_GPIO_PIN_9_EDGE_FALL, DL_GPIO_PIN_9_EDGE_RISE_FALL},
    {GPIOA, DL_GPIO_PIN_25, 25, IOMUX_PINCM55, 2, PWM_TIMER_TIMA0, 3, IOMUX_PINCM55_PF_TIMA0_CCP3, DL_GPIO_PIN_25_EDGE_DISABLE, DL_GPIO_PIN_25_EDGE_RISE, DL_GPIO_PIN_25_EDGE_FALL, DL_GPIO_PIN_25_EDGE_RISE_FALL},
    {GPIOB, DL_GPIO_PIN_25, 25, IOMUX_PINCM56, 4, PWM_TIMER_NONE, 0, 0, DL_GPIO_PIN_25_EDGE_DISABLE, DL_GPIO_PIN_25_EDGE_RISE, DL_GPIO_PIN_25_EDGE_FALL, DL_GPIO_PIN_25_EDGE_RISE_FALL},
    {GPIOA, DL_GPIO_PIN_26, 26, IOMUX_PINCM59, 1, PWM_TIMER_NONE, 0, 0, DL_GPIO_PIN_26_EDGE_DISABLE, DL_GPIO_PIN_26_EDGE_RISE, DL_GPIO_PIN_26_EDGE_FALL, DL_GPIO_PIN_26_EDGE_RISE_FALL},
    {GPIOA, DL_GPIO_PIN_27, 27, IOMUX_PINCM60, 0, PWM_TIMER_NONE, 0, 0, DL_GPIO_PIN_27_EDGE_DISABLE, DL_GPIO_PIN_27_EDGE_RISE, DL_GPIO_PIN_27_EDGE_FALL, DL_GPIO_PIN_27_EDGE_RISE_FALL},
    {GPIOA, DL_GPIO_PIN_9, 9, IOMUX_PINCM20, 0xFF, PWM_TIMER_NONE, 0, 0, DL_GPIO_PIN_9_EDGE_DISABLE, DL_GPIO_PIN_9_EDGE_RISE, DL_GPIO_PIN_9_EDGE_FALL, DL_GPIO_PIN_9_EDGE_RISE_FALL},
    {GPIOB, DL_GPIO_PIN_23, 23, IOMUX_PINCM51, 0xFF, PWM_TIMER_NONE, 0, 0, DL_GPIO_PIN_23_EDGE_DISABLE, DL_GPIO_PIN_23_EDGE_RISE, DL_GPIO_PIN_23_EDGE_FALL, DL_GPIO_PIN_23_EDGE_RISE_FALL},
    {GPIOA, DL_GPIO_PIN_8, 8, IOMUX_PINCM19, 0xFF, PWM_TIMER_NONE, 0, 0, DL_GPIO_PIN_8_EDGE_DISABLE, DL_GPIO_PIN_8_EDGE_RISE, DL_GPIO_PIN_8_EDGE_FALL, DL_GPIO_PIN_8_EDGE_RISE_FALL},
    {GPIOB, DL_GPIO_PIN_15, 15, IOMUX_PINCM32, 0xFF, PWM_TIMER_NONE, 0, 0, DL_GPIO_PIN_15_EDGE_DISABLE, DL_GPIO_PIN_15_EDGE_RISE, DL_GPIO_PIN_15_EDGE_FALL, DL_GPIO_PIN_15_EDGE_RISE_FALL},
    {GPIOB, DL_GPIO_PIN_17, 17, IOMUX_PINCM43, 0xFF, PWM_TIMER_NONE, 0, 0, DL_GPIO_PIN_17_EDGE_DISABLE, DL_GPIO_PIN_17_EDGE_RISE, DL_GPIO_PIN_17_EDGE_FALL, DL_GPIO_PIN_17_EDGE_RISE_FALL},
    {GPIOB, DL_GPIO_PIN_12, 12, IOMUX_PINCM29, 0xFF, PWM_TIMER_NONE, 0, 0, DL_GPIO_PIN_12_EDGE_DISABLE, DL_GPIO_PIN_12_EDGE_RISE, DL_GPIO_PIN_12_EDGE_FALL, DL_GPIO_PIN_12_EDGE_RISE_FALL},
    {GPIOB, DL_GPIO_PIN_24, 24, IOMUX_PINCM52, 5, PWM_TIMER_NONE, 0, 0, DL_GPIO_PIN_24_EDGE_DISABLE, DL_GPIO_PIN_24_EDGE_RISE, DL_GPIO_PIN_24_EDGE_FALL, DL_GPIO_PIN_24_EDGE_RISE_FALL},
    {GPIOB, DL_GPIO_PIN_0, 0, IOMUX_PINCM12, 0xFF, PWM_TIMER_NONE, 0, 0, DL_GPIO_PIN_0_EDGE_DISABLE, DL_GPIO_PIN_0_EDGE_RISE, DL_GPIO_PIN_0_EDGE_FALL, DL_GPIO_PIN_0_EDGE_RISE_FALL},
    {GPIOB, DL_GPIO_PIN_1, 1, IOMUX_PINCM13, 0xFF, PWM_TIMER_NONE, 0, 0, DL_GPIO_PIN_1_EDGE_DISABLE, DL_GPIO_PIN_1_EDGE_RISE, DL_GPIO_PIN_1_EDGE_FALL, DL_GPIO_PIN_1_EDGE_RISE_FALL},
    {GPIOB, DL_GPIO_PIN_4, 4, IOMUX_PINCM17, 0xFF, PWM_TIMER_NONE, 0, 0, DL_GPIO_PIN_4_EDGE_DISABLE, DL_GPIO_PIN_4_EDGE_RISE, DL_GPIO_PIN_4_EDGE_FALL, DL_GPIO_PIN_4_EDGE_RISE_FALL},
    {GPIOB, DL_GPIO_PIN_16, 16, IOMUX_PINCM33, 0xFF, PWM_TIMER_NONE, 0, 0, DL_GPIO_PIN_16_EDGE_DISABLE, DL_GPIO_PIN_16_EDGE_RISE, DL_GPIO_PIN_16_EDGE_FALL, DL_GPIO_PIN_16_EDGE_RISE_FALL},
    {GPIOB, DL_GPIO_PIN_19, 19, IOMUX_PINCM45, 0xFF, PWM_TIMER_NONE, 0, 0, DL_GPIO_PIN_19_EDGE_DISABLE, DL_GPIO_PIN_19_EDGE_RISE, DL_GPIO_PIN_19_EDGE_FALL, DL_GPIO_PIN_19_EDGE_RISE_FALL},
    {GPIOA, DL_GPIO_PIN_28, 28, IOMUX_PINCM3, 0xFF, PWM_TIMER_NONE, 0, 0, DL_GPIO_PIN_28_EDGE_DISABLE, DL_GPIO_PIN_28_EDGE_RISE, DL_GPIO_PIN_28_EDGE_FALL, DL_GPIO_PIN_28_EDGE_RISE_FALL},
    {GPIOA, DL_GPIO_PIN_22, 22, IOMUX_PINCM47, 7, PWM_TIMER_NONE, 0, 0, DL_GPIO_PIN_22_EDGE_DISABLE, DL_GPIO_PIN_22_EDGE_RISE, DL_GPIO_PIN_22_EDGE_FALL, DL_GPIO_PIN_22_EDGE_RISE_FALL},
    {GPIOA, DL_GPIO_PIN_31, 31, IOMUX_PINCM6, 0xFF, PWM_TIMER_NONE, 0, 0, DL_GPIO_PIN_31_EDGE_DISABLE, DL_GPIO_PIN_31_EDGE_RISE, DL_GPIO_PIN_31_EDGE_FALL, DL_GPIO_PIN_31_EDGE_RISE_FALL},
    {GPIOB, DL_GPIO_PIN_18, 18, IOMUX_PINCM44, 0xFF, PWM_TIMER_NONE, 0, 0, DL_GPIO_PIN_18_EDGE_DISABLE, DL_GPIO_PIN_18_EDGE_RISE, DL_GPIO_PIN_18_EDGE_FALL, DL_GPIO_PIN_18_EDGE_RISE_FALL},
    {GPIOB, DL_GPIO_PIN_20, 20, IOMUX_PINCM48, 6, PWM_TIMER_NONE, 0, 0, DL_GPIO_PIN_20_EDGE_DISABLE, DL_GPIO_PIN_20_EDGE_RISE, DL_GPIO_PIN_20_EDGE_FALL, DL_GPIO_PIN_20_EDGE_RISE_FALL},
    {GPIOB, DL_GPIO_PIN_13, 13, IOMUX_PINCM30, 0xFF, PWM_TIMER_NONE, 0, 0, DL_GPIO_PIN_13_EDGE_DISABLE, DL_GPIO_PIN_13_EDGE_RISE, DL_GPIO_PIN_13_EDGE_FALL, DL_GPIO_PIN_13_EDGE_RISE_FALL},
    {GPIOA, DL_GPIO_PIN_24, 24, IOMUX_PINCM54, 3, PWM_TIMER_NONE, 0, 0, DL_GPIO_PIN_24_EDGE_DISABLE, DL_GPIO_PIN_24_EDGE_RISE, DL_GPIO_PIN_24_EDGE_FALL, DL_GPIO_PIN_24_EDGE_RISE_FALL},
    {GPIOA, DL_GPIO_PIN_17, 17, IOMUX_PINCM39, 0xFF, PWM_TIMER_NONE, 0, 0, DL_GPIO_PIN_17_EDGE_DISABLE, DL_GPIO_PIN_17_EDGE_RISE, DL_GPIO_PIN_17_EDGE_FALL, DL_GPIO_PIN_17_EDGE_RISE_FALL},
    {GPIOA, DL_GPIO_PIN_16, 16, IOMUX_PINCM38, 0xFF, PWM_TIMER_NONE, 0, 0, DL_GPIO_PIN_16_EDGE_DISABLE, DL_GPIO_PIN_16_EDGE_RISE, DL_GPIO_PIN_16_EDGE_FALL, DL_GPIO_PIN_16_EDGE_RISE_FALL},
    {GPIOA, DL_GPIO_PIN_12, 12, IOMUX_PINCM34, 0xFF, PWM_TIMER_NONE, 0, 0, DL_GPIO_PIN_12_EDGE_DISABLE, DL_GPIO_PIN_12_EDGE_RISE, DL_GPIO_PIN_12_EDGE_FALL, DL_GPIO_PIN_12_EDGE_RISE_FALL},
    {GPIOA, DL_GPIO_PIN_13, 13, IOMUX_PINCM35, 0xFF, PWM_TIMER_NONE, 0, 0, DL_GPIO_PIN_13_EDGE_DISABLE, DL_GPIO_PIN_13_EDGE_RISE, DL_GPIO_PIN_13_EDGE_FALL, DL_GPIO_PIN_13_EDGE_RISE_FALL},
    {GPIOA, DL_GPIO_PIN_15, 15, IOMUX_PINCM37, 0xFF, PWM_TIMER_NONE, 0, 0, DL_GPIO_PIN_15_EDGE_DISABLE, DL_GPIO_PIN_15_EDGE_RISE, DL_GPIO_PIN_15_EDGE_FALL, DL_GPIO_PIN_15_EDGE_RISE_FALL},
};

extern "C" void initVariant(void)
{
}
